{
  "formatVersion": "1.1",
  "component": {
    "group": "committee.nova",
    "module": "lighteco",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lighteco-1.0.0.jar",
          "url": "lighteco-1.0.0.jar",
          "size": 11512,
          "sha512": "6c28745f4bfdc2c86e500cf00f462979ec1b17651af2be5fff26fe7aca93fe2613d71cdcd7135e11034f0ad12c59c0a8de8797ac2b66769bdd5965e599f1add6",
          "sha256": "d2a35f1727eaf6cab8bb0ed4c585aa3be29573a83dcf730923496e1067079bf4",
          "sha1": "3a436ec9ce81bcdbb3430da1f722368996a025c0",
          "md5": "09c107359ea5728381daad3e3c65f760"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.18.2-40.2.0_mapped_official_1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "lighteco-1.0.0.jar",
          "url": "lighteco-1.0.0.jar",
          "size": 11512,
          "sha512": "6c28745f4bfdc2c86e500cf00f462979ec1b17651af2be5fff26fe7aca93fe2613d71cdcd7135e11034f0ad12c59c0a8de8797ac2b66769bdd5965e599f1add6",
          "sha256": "d2a35f1727eaf6cab8bb0ed4c585aa3be29573a83dcf730923496e1067079bf4",
          "sha1": "3a436ec9ce81bcdbb3430da1f722368996a025c0",
          "md5": "09c107359ea5728381daad3e3c65f760"
        }
      ]
    }
  ]
}
